### ISSUE TITLE
Change of license?

### ISSUE THREAD

**Issue by kpet** [krrishnarraj/clpeak#110]
First of all, thank you for this project that a growing number of folks are finding useful. Its current license is a barrier to many companies being able to contribute. Would you consider changing the license to an industry-standard one such as Apache-2.0?

**Comment by krrishnarraj** [comment]
Done

**Comment by kpet** [comment]
Many thanks for doing this, it should enable more companies to contribute. I _think_ your changes should satisfy our needs at least but I am not a lawyer. I'll close this issue optimistically and re-open it in case further changes are highlighted as part of our review process.
