### ISSUE TITLE
result for AMD RX 6600 in macOS 14.4

### ISSUE THREAD

**Issue by cfwen** [krrishnarraj/clpeak#113]
Platform: Apple
  Device: AMD Radeon RX 6600 Compute Engine
    Driver version  : 1.2 (Feb 21 2024 21:44:18) (Macintosh)
    Compute units   : 28
    Clock frequency : 2750 MHz

    Global memory bandwidth (GBPS)
      float   : 199.54
      float2  : 207.46
      float4  : 211.33
      float8  : 209.29
      float16 : 177.12

    Single-precision compute (GFLOPS)
      float   : 4390.59
      float2  : 4382.19
      float4  : 4342.84
      float8  : 4324.32
      float16 : 4204.27

    No half precision support! Skipped

    Double-precision compute (GFLOPS)
      double   : 554.49
      double2  : 553.16
      double4  : 551.83
      double8  : 544.15
      double16 : 545.67

    Integer compute (GIOPS)
      int   : 1735.16
      int2  : 1721.56
      int4  : 1717.33
      int8  : 1692.05
      int16 : 1706.22

    Integer compute Fast 24bit (GIOPS)
      int   : 7663.00
      int2  : 7561.06
      int4  : 7510.31
      int8  : 7338.48
      int16 : 7299.52

    Transfer bandwidth (GBPS)
      enqueueWriteBuffer              : 11.93
      enqueueReadBuffer               : 13.49
      enqueueWriteBuffer non-blocking : 12.64
      enqueueReadBuffer non-blocking  : 13.55
      enqueueMapBuffer(for read)      : 91.02
        memcpy from mapped ptr        : 10.43
      enqueueUnmap(after write)       : 34458.03
        memcpy to mapped ptr          : 10.52

    Kernel launch latency : 5.57 us

**Comment by cfwen** [comment]
single precision performance is only half of theoretic performance

**Comment by cfwen** [comment]
for same hardware, in Ubuntu 20.04, single precision performance is close to theoretic performance

**Comment by krrishnarraj** [comment]
Apple is not actively maintaining support for OpenCL
