### ISSUE TITLE
Does not build on OS X due to missing OpenCL C++ bindings.

### ISSUE THREAD

**Issue by he-sk** [krrishnarraj/clpeak#21]
OS X El Capitan does not ship the cl.hpp headers. I think the license permits to just include this file in the sources.

**Comment by krrishnarraj** [comment]
I have made some changes.
Could you check now with devel branch and confirm

**Comment by he-sk** [comment]
I've created a pull request based on the devel branch.

**Comment by he-sk** [comment]
Just tested this on OS X and while it does compile, it hangs after printing the version info.

The master branch worked yesterday. So, some commit in the devel branch breaks the program on OS X.

I'll investigate later.

**Comment by he-sk** [comment]
Seems like commit 2aa9805e (remove platform specific disables) is the culprit. If I back it out it works on OS X. Any idea what might cause the hang?

**Comment by krrishnarraj** [comment]
integer kernels were previously disabled due to compilation problem in apple platform.
Thought would be fixed by now. sigh!
I will revert that commit

**Comment by krrishnarraj** [comment]
Could you check now if devel branch is clean on apple?

Thanks BTW

**Comment by he-sk** [comment]
It works now. I've created a pull request with a report on Apple Iris.
