### ISSUE TITLE
`half`  should not be passed as kernel argument

### ISSUE THREAD

**Issue by Oblomov** [krrishnarraj/clpeak#29]
The compute kernels testing half-precision performance pass a `half` value as kernel argument, even though this is forbidden by the specification (see the relevant bullet point [here](https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/restrictions.html).

A possible solution would be to pass the extra argument as an int and then cast as appropriate.

(Most platforms seem to accept it, but `beignet` follows the spec more closely.)

**Comment by krrishnarraj** [comment]
@Oblomov tried fixing this in 2fb43e4, but I am getting a runtime error/coredump

> Platform: Intel Gen OCL Driver
> drm_intel_gem_bo_context_exec() failed: Device or resource busy
> Beignet: "Exec event 0x556754c88fa0 error, type is 4592, error status is -5"
>   Device: Intel(R) HD Graphics Haswell GT2 Mobile
>     Driver version  : 1.4 (Linux x64)
>     Compute units   : 20
>     Clock frequency : 1000 MHz
> ASSERTION FAILED: Not supported
>   at file ... beignet/backend/src/backend/gen_insn_selection.cpp, function uint32_t gbe::getByteScatterGatherSize(gbe::Selection::Opaque&, gbe::ir::Type), line 4050
> Trace/breakpoint trap (core dumped)

Can you check this commit in devel branch?

**Comment by Oblomov** [comment]
I get the same error. The commit seems correct to me, so there is the possibility that this is an issue in Beignet itself. I'll try to have a look at it (I'm somewhat busy right now, so this might take some time).
