### ISSUE TITLE
commit 7904f26499851488461fdbaad5667a09ba8ea920 fails to build on aarch64/ppc64 w/ gcc7

### ISSUE THREAD

**Issue by rosset** [krrishnarraj/clpeak#36]
logs here:
https://kojipkgs.fedoraproject.org//work/tasks/6222/20056222/build.log
https://koji.fedoraproject.org/koji/taskinfo?taskID=20056219

[ 30%] Building CXX object CMakeFiles/clpeak.dir/src/logger.cpp.o
/usr/bin/c++   -I/builddir/build/BUILD/clpeak-7904f26499851488461fdbaad5667a09ba8ea920/deps/OpenCL-CLHPP/include -I/builddir/build/BUILD/clpeak-7904f26499851488461fdbaad5667a09ba8ea920/include -I/builddir/build/BUILD/clpeak-7904f26499851488461fdbaad5667a09ba8ea920/src/kernels  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -DNDEBUG   -std=gnu++11 -march=native -fPIC -Wall -Wextra -Wno-deprecated-declarations -Wno-unused-parameter -Wno-ignored-attributes -o CMakeFiles/clpeak.dir/src/logger.cpp.o -c /builddir/build/BUILD/clpeak-7904f26499851488461fdbaad5667a09ba8ea920/src/logger.cpp
/builddir/build/BUILD/clpeak-7904f26499851488461fdbaad5667a09ba8ea920/src/clpeak.cpp: In member function 'int clPeak::runAll()':
/builddir/build/BUILD/clpeak-7904f26499851488461fdbaad5667a09ba8ea920/src/clpeak.cpp:51:33: error: 'OS_NAME' was not declared in this scope
     log->xmlAppendAttribs("os", OS_NAME);
                                 ^~~~~~~
/builddir/build/BUILD/clpeak-7904f26499851488461fdbaad5667a09ba8ea920/src/clpeak.cpp:51:33: note: suggested alternative: 'LC_NAME'
     log->xmlAppendAttribs("os", OS_NAME);
                                 ^~~~~~~
                                 LC_NAME
/builddir/build/BUILD/clpeak-7904f26499851488461fdbaad5667a09ba8ea920/src/clpeak.cpp:105:61: error: expected ')' before 'OS_NAME'
         log->print(devInfo.driverVersion);  log->print(" (" OS_NAME ")" NEWLINE);
                                                             ^~~~~~~
make[2]: *** [CMakeFiles/clpeak.dir/build.make:90: CMakeFiles/clpeak.dir/src/clpeak.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/builddir/build/BUILD/clpeak-7904f26499851488461fdbaad5667a09ba8ea920/build'
make[1]: Leaving directory '/builddir/build/BUILD/clpeak-7904f26499851488461fdbaad5667a09ba8ea920/build'
make[1]: *** [CMakeFiles/Makefile2:71: CMakeFiles/clpeak.dir/all] Error 2

**Comment by krrishnarraj** [comment]
Could you confirm with this commit?

**Comment by rosset** [comment]
The error is different now,
gcc: error: unrecognized command line option ‘-march=native’

maybe should try with -mtune=native 

I'll look further tomorrow (it's a bit late here GMT-3)

https://koji.fedoraproject.org/koji/taskinfo?taskID=20062558
https://kojipkgs.fedoraproject.org//work/tasks/2560/20062560/build.log

[ 23%] Building CXX object CMakeFiles/clpeak.dir/src/options.cpp.o
/usr/bin/c++   -I/builddir/build/BUILD/clpeak-c0b1f3f2d63a0b4c9f0ac4b3fc6f4034fed34f26/deps/OpenCL-CLHPP/include -I/builddir/build/BUILD/clpeak-c0b1f3f2d63a0b4c9f0ac4b3fc6f4034fed34f26/include -I/builddir/build/BUILD/clpeak-c0b1f3f2d63a0b4c9f0ac4b3fc6f4034fed34f26/src/kernels  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mcpu=power8 -mtune=power8 -DNDEBUG   -std=gnu++11 -march=native -fPIC -Wall -Wextra -Wno-deprecated-declarations -Wno-unused-parameter -Wno-ignored-attributes -o CMakeFiles/clpeak.dir/src/clpeak.cpp.o -c /builddir/build/BUILD/clpeak-c0b1f3f2d63a0b4c9f0ac4b3fc6f4034fed34f26/src/clpeak.cpp
/usr/bin/c++   -I/builddir/build/BUILD/clpeak-c0b1f3f2d63a0b4c9f0ac4b3fc6f4034fed34f26/deps/OpenCL-CLHPP/include -I/builddir/build/BUILD/clpeak-c0b1f3f2d63a0b4c9f0ac4b3fc6f4034fed34f26/include -I/builddir/build/BUILD/clpeak-c0b1f3f2d63a0b4c9f0ac4b3fc6f4034fed34f26/src/kernels  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mcpu=power8 -mtune=power8 -DNDEBUG   -std=gnu++11 -march=native -fPIC -Wall -Wextra -Wno-deprecated-declarations -Wno-unused-parameter -Wno-ignored-attributes -o CMakeFiles/clpeak.dir/src/options.cpp.o -c /builddir/build/BUILD/clpeak-c0b1f3f2d63a0b4c9f0ac4b3fc6f4034fed34f26/src/options.cpp
cc1plus: error: unrecognized command line option '-march=native'
cc1plus: error: unrecognized command line option '-march=native'
cc1plus: error: unrecognized command line option '-march=native'
make[2]: *** [CMakeFiles/clpeak.dir/build.make:66: CMakeFiles/clpeak.dir/src/common.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/clpeak.dir/build.make:90: CMakeFiles/clpeak.dir/src/clpeak.cpp.o] Error 1
[ 30%] Building CXX object CMakeFiles/clpeak.dir/src/logger.cpp.o
make[2]: *** [CMakeFiles/clpeak.dir/build.make:114: CMakeFiles/clpeak.dir/src/options.cpp.o] Error 1
/usr/bin/c++   -I/builddir/build/BUILD/clpeak-c0b1f3f2d63a0b4c9f0ac4b3fc6f4034fed34f26/deps/OpenCL-CLHPP/include -I/builddir/build/BUILD/clpeak-c0b1f3f2d63a0b4c9f0ac4b3fc6f4034fed34f26/include -I/builddir/build/BUILD/clpeak-c0b1f3f2d63a0b4c9f0ac4b3fc6f4034fed34f26/src/kernels  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mcpu=power8 -mtune=power8 -DNDEBUG   -std=gnu++11 -march=native -fPIC -Wall -Wextra -Wno-deprecated-declarations -Wno-unused-parameter -Wno-ignored-attributes -o CMakeFiles/clpeak.dir/src/logger.cpp.o -c /builddir/build/BUILD/clpeak-c0b1f3f2d63a0b4c9f0ac4b3fc6f4034fed34f26/src/logger.cpp
cc1plus: error: unrecognized command line option '-march=native'
make[2]: *** [CMakeFiles/clpeak.dir/build.make:138: CMakeFiles/clpeak.dir/src/logger.cpp.o] Error 1
make[2]: Leaving directory '/builddir/build/BUILD/clpeak-c0b1f3f2d63a0b4c9f0ac4b3fc6f4034fed34f26/build'
make[1]: *** [CMakeFiles/Makefile2:71: CMakeFiles/clpeak.dir/all] Error 2
make[1]: Leaving directory '/builddir/build/BUILD/clpeak-c0b1f3f2d63a0b4c9f0ac4b3fc6f4034fed34f26/build'
make: *** [Makefile:87: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.5vQs6i (%build)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.5vQs6i (%build)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.5/site-packages/mockbuild/util.py", line 582, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
mockbuild.exception.Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target ppc64le --nodeps /builddir/build/SPECS/clpeak.spec

**Comment by krrishnarraj** [comment]
This should fix ppc build issue

**Comment by rosset** [comment]
I can confirm it's fixed, thank you.
