### ISSUE TITLE
Is there a usage guide of this tool from build to use?

### ISSUE THREAD

**Issue by ysh329** [krrishnarraj/clpeak#44]
I want to measure OpenCL peak of my device. But I'm new to C/C++ project. I just executed these line below:
```Shell
cd clpeak
mkdir build
cd build
cmake ..
```
eh,

**Comment by krrishnarraj** [comment]
followed by:

> make
> ./clpeak

There is no usage guide as yet

**Comment by ysh329** [comment]
Thanks

**Comment by ysh329** [comment]
@krrishnarraj I tried, but failed
```
ysh329@firefly:~/code/clpeak$ make
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by krrishnarraj** [comment]
make is to be done on build folder
```
mkdir build
cd build
cmake ..
make
./clpeak
```

**Comment by ysh329** [comment]
Thanks, my big brother! :rofl:
