### ISSUE TITLE
Can you make a new stable release?

### ISSUE THREAD

**Issue by svenstaro** [krrishnarraj/clpeak#53]
The last release was in 2015. I think you should make a new release so that this tool has a better chance of getting into distros.

**Comment by svenstaro** [comment]
@krrishnarraj ping

**Comment by svenstaro** [comment]
@krrishnarraj pretty please :)

**Comment by krrishnarraj** [comment]
Haha
I don't have a mac. If somebody can let me know if master branch runs fine on mac, I'll make the release

**Comment by ahti** [comment]
On my mid 2015 MBP the tool runs fine using the dedicated GPU. Using the integrated one freezes the system during the integer compute tests.

This message appears quite a bit in console before the crash:

    void IOAccelFenceMachine::fence_timeout(IOTimerEventSource *): IntelAccelerator prodding blockFenceInterrupt

**Comment by krrishnarraj** [comment]
That looks like a driver error, which I'll pass.
I'll make a release in few days

**Comment by svenstaro** [comment]
Great! Looking forward to 1.0.0. :D
