### ISSUE TITLE
Add lib64 EGL libGLES_mali.so

### ISSUE THREAD

**Issue by paranlee** [krrishnarraj/clpeak#81]
In main MainActivity.java program. libopenclSoPaths have /system/lib/egl/libGLES_mali.so in 32bit.

Android ≥ 9 in 64bit Exynos SoC that equiped mali GPU have /system/lib/egl/libGLES_mali.so

**Comment by paranlee** [comment]
Pull Request #80 Add this file path on this issue.

**Comment by krrishnarraj** [comment]
PR merged

**Comment by paranlee** [comment]
@krrishnarraj Thanks for making such great software!
