### ISSUE TITLE
Making a new release to fix #73

### ISSUE THREAD

**Issue by r-value** [krrishnarraj/clpeak#83]
`clpeak` is getting packaged and I found that release `1.1.0` is no longer able to be built because of the deprecation of `<CL/cl.hpp>` which is mentioned in #73 and fixed in [this commit](https://github.com/krrishnarraj/clpeak/commit/db42d30028bace27cda3c7d95f122a5c14743246). Could you please release the change so that it can be packaged?

**Comment by krrishnarraj** [comment]
https://github.com/krrishnarraj/clpeak/releases/tag/1.1.1
