### ISSUE TITLE
Unable to get debug mode in clpeak

### ISSUE THREAD

**Issue by aditikau** [krrishnarraj/clpeak#84]
I need to run gdb over the clpeak but I was getting "No Debugging Symbols found" warning.
Thus, to fix this I tried putting -g option in cmake commands in MakeFile but still it is not working for me.

Can anyone please share steps on how I can enable this ?

**Comment by doe300** [comment]
Usually, setting the CMake variable `CMAKE_BUILD_TYPE` to `Debug` should to the trick, e.g. calling with `cmake -DCMAKE_BUILD_TYPE=Debug [other options] <path/to/sources>`

**Comment by krrishnarraj** [comment]
https://riptutorial.com/cmake/example/7357/switching-between-build-types--e-g--debug-and-release
Pass -DCMAKE_BUILD_TYPE=Debug to cmake

**Comment by aditikau** [comment]
Thanks @krrishnarraj . It worked :)
