### ISSUE TITLE
Build project failed

### ISSUE THREAD

**Issue by malixian** [krrishnarraj/clpeak#85]
Run command `cmake ..`, build failed log is:

> [ 25%] Building C object CMakeFiles/OpenCL.dir/icd.c.o
In file included from /home/mlx/clpeak/build/icd/build/icd/src/icd/./inc/CL/cl.h:20,
                 from /home/mlx/clpeak/build/icd/build/icd/src/icd/icd.h:53,
                 from /home/mlx/clpeak/build/icd/build/icd/src/icd/icd.c:38:
/home/mlx/clpeak/build/icd/build/icd/src/icd/./inc/CL/cl_version.h:22:9: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)
   22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")
      |         ^~~~~~~
In file included from /home/mlx/clpeak/build/icd/build/icd/src/icd/icd_dispatch.h:70,
                 from /home/mlx/clpeak/build/icd/build/icd/src/icd/icd.c:39:
/home/mlx/clpeak/build/icd/build/icd/src/icd/./inc/CL/cl_gl_ext.h:18:9: note: #pragma message: All OpenGL-related extensions have been moved into cl_gl.h.  Please include cl_gl.h directly.
   18 | #pragma message("All OpenGL-related extensions have been moved into cl_gl.h.  Please include cl_gl.h directly.")
      |         ^~~~~~~
In file included from /home/mlx/clpeak/build/icd/build/icd/src/icd/icd.c:39:
/home/mlx/clpeak/build/icd/build/icd/src/icd/icd_dispatch.h:418:56: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘CL_EXT_SUFFIX__VERSION_2_0’
  418 |     size_t*                  /*param_value_size_ret*/) CL_EXT_SUFFIX__VERSION_2_0;
      |                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mlx/clpeak/build/icd/build/icd/src/icd/icd_dispatch.h:756:51: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘CL_EXT_SUFFIX__VERSION_1_0_DEPRECATED’
  756 |     cl_command_queue_properties * old_properties) CL_EXT_SUFFIX__VERSION_1_0_DEPRECATED;
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mlx/clpeak/build/icd/build/icd/src/icd/icd_dispatch.h:766:42: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED’
  766 |     cl_int *                errcode_ret) CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED;
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mlx/clpeak/build/icd/build/icd/src/icd/icd_dispatch.h:778:42: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED’
  778 |     cl_int *                errcode_ret) CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED;
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mlx/clpeak/build/icd/build/icd/src/icd/icd_dispatch.h:780:74: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED’
  780 | typedef CL_API_ENTRY cl_int (CL_API_CALL *KHRpfn_clUnloadCompiler)(void) CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED;
      |                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mlx/clpeak/build/icd/build/icd/src/icd/icd_dispatch.h:784:32: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED’
  784 |     cl_event *          event) CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED;
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mlx/clpeak/build/icd/build/icd/src/icd/icd_dispatch.h:789:34: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED’
  789 |     const cl_event * event_list) CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED;
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mlx/clpeak/build/icd/build/icd/src/icd/icd_dispatch.h:791:100: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED’
  791 | typedef CL_API_ENTRY cl_int (CL_API_CALL *KHRpfn_clEnqueueBarrier)(cl_command_queue command_queue) CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED;
      |                                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/mlx/clpeak/build/icd/build/icd/src/icd/icd.c:39:
/home/mlx/clpeak/build/icd/build/icd/src/icd/icd_dispatch.h:793:108: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED’
  793 | typedef CL_API_ENTRY void * (CL_API_CALL *KHRpfn_clGetExtensionFunctionAddress)(const char *function_name) CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED;
      |                                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mlx/clpeak/build/icd/build/icd/src/icd/icd_dispatch.h:1317:5: error: unknown type name ‘KHRpfn_clSetCommandQueueProperty’
 1317 |     KHRpfn_clSetCommandQueueProperty                clSetCommandQueueProperty;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mlx/clpeak/build/icd/build/icd/src/icd/icd_dispatch.h:1319:5: error: unknown type name ‘KHRpfn_clCreateImage2D’
 1319 |     KHRpfn_clCreateImage2D                          clCreateImage2D;
      |     ^~~~~~~~~~~~~~~~~~~~~~
/home/mlx/clpeak/build/icd/build/icd/src/icd/icd_dispatch.h:1320:5: error: unknown type name ‘KHRpfn_clCreateImage3D’
 1320 |     KHRpfn_clCreateImage3D                          clCreateImage3D;
      |     ^~~~~~~~~~~~~~~~~~~~~~
/home/mlx/clpeak/build/icd/build/icd/src/icd/icd_dispatch.h:1335:5: error: unknown type name ‘KHRpfn_clUnloadCompiler’
 1335 |     KHRpfn_clUnloadCompiler                         clUnloadCompiler;
      |     ^~~~~~~~~~~~~~~~~~~~~~~
/home/mlx/clpeak/build/icd/build/icd/src/icd/icd_dispatch.h:1366:5: error: unknown type name ‘KHRpfn_clEnqueueMarker’
 1366 |     KHRpfn_clEnqueueMarker                          clEnqueueMarker;
      |     ^~~~~~~~~~~~~~~~~~~~~~
/home/mlx/clpeak/build/icd/build/icd/src/icd/icd_dispatch.h:1367:5: error: unknown type name ‘KHRpfn_clEnqueueWaitForEvents’
 1367 |     KHRpfn_clEnqueueWaitForEvents                   clEnqueueWaitForEvents;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mlx/clpeak/build/icd/build/icd/src/icd/icd_dispatch.h:1368:5: error: unknown type name ‘KHRpfn_clEnqueueBarrier’
 1368 |     KHRpfn_clEnqueueBarrier                         clEnqueueBarrier;
      |     ^~~~~~~~~~~~~~~~~~~~~~~
/home/mlx/clpeak/build/icd/build/icd/src/icd/icd_dispatch.h:1369:5: error: unknown type name ‘KHRpfn_clGetExtensionFunctionAddress’
 1369 |     KHRpfn_clGetExtensionFunctionAddress            clGetExtensionFunctionAddress;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mlx/clpeak/build/icd/build/icd/src/icd/icd_dispatch.h:1462:5: error: unknown type name ‘KHRpfn_clGetKernelSubGroupInfoKHR’
 1462 |     KHRpfn_clGetKernelSubGroupInfoKHR               clGetKernelSubGroupInfoKHR;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[5]: *** [CMakeFiles/OpenCL.dir/build.make:63: CMakeFiles/OpenCL.dir/icd.c.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:76: CMakeFiles/OpenCL.dir/all] Error 2
make[3]: *** [Makefile:130: all] Error 2
make[2]: *** [CMakeFiles/icd_build.dir/build.make:114: icd/src/icd_build-stamp/icd_build-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:81: CMakeFiles/icd_build.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find OpenCL (missing: OpenCL_LIBRARY OpenCL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindOpenCL.cmake:150 (find_package_handle_standard_args)
  CMakeLists.txt:17 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by krrishnarraj** [comment]
Fixed in #87
